name: Run

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  update-trading212-spreadsheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Start Application
        run: npm start
