name: Run

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 * * * *'

jobs:
  update-trading212-spreadsheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - run: npm install
      - run: npm start
